import type { Metadata } from "next";
import { Playwrite_DK_Loopet } from 'next/font/google';
import "./globals.css";

const playwriteDKLoopet = Playwrite_DK_Loopet({
  display: 'swap',
  weight: '400',
  variable: '--font-playwrite-dk-loopet',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link 
          href="https://fonts.googleapis.com/css2?family=Playwrite+DK+Loopet&display=swap" 
          rel="stylesheet" 
        />
        <link 
          href="https://cdn.jsdelivr.net/npm/@fontsource/cascadia-code/index.css"
          rel="stylesheet" 
        />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}